spring:
  application:
    name: chapter2

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:/Users/rishabhkumar/Downloads/chapter2/db
    username: RishabhDB
    password: Rishabh123
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
